version: 0.1.1
default:
  POSTGRES_CONNECT_TIMEOUT: 10
  POSTGRES_DBNAME: machine
  POSTGRES_SCHEMA: public # Optional
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: password
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432version: 0.1.1