# Use the base image from the original docker-compose file
FROM jupyter/base-notebook:latest

# Set the working directory inside the container
WORKDIR /project

# Install additional packages
RUN python3 -m pip install pandas

# Expose the port that the Jupyter Notebook will run on
EXPOSE 8888

# Command to run Jupyter Notebook without a token
CMD ["sh", "-c", "start-notebook.sh --NotebookApp.token=''"]