version: '3.8'

services:
  mage:
    image: mageai/mageai:latest
    container_name: magic
    env_file:
      - .env
    environment:
      ENV: dev
      POSTGRES_DB: ${POSTGRES_SCHEMA}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      PG_HOST_PORT: ${PG_HOST_PORT}
      ALPHAVINTAGE_API_KEY: ${ALPHAVINTAGE_API_KEY}
    ports:
      - 6789:6789
    volumes:
      - ./workflow:/home/src/default_repo/workflow
    depends_on:
      - postgres
    command: mage start magic
    restart: on-failure:5

  postgres:
    image: postgres:latest
    restart: on-failure
    container_name: postgres-magic
    build:
      context: ./db
    env_file:
      - .env
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-magic
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: mage@email.com
      PGADMIN_DEFAULT_PASSWORD: 12345
    depends_on:
      - postgres