version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: bank_account
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: local_pgadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: project1@email.com
      PGADMIN_DEFAULT_PASSWORD: 12345
    depends_on:
      - postgres
