version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pgadmin_user
      POSTGRES_PASSWORD: pgadmin_password
  pgadmin:
    image: dpage/pgadmin4
    container_name: local_pgadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin_password
    depends_on:
      - postgres
